// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVaL-UA4L2MZQTQDUqD-8NZ7V8GljyFgQ',
    appId: '1:310448288775:web:768db82571e0534da9a6a2',
    messagingSenderId: '310448288775',
    projectId: 'practica-flutter-firebase-arce',
    authDomain: 'practica-flutter-firebase-arce.firebaseapp.com',
    storageBucket: 'practica-flutter-firebase-arce.appspot.com',
    measurementId: 'G-T6KMPMNC6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxsqsvrjli_WcY6Ea3kPSaqOrNDml4I-I',
    appId: '1:310448288775:android:5e97a0e5b72a1d9aa9a6a2',
    messagingSenderId: '310448288775',
    projectId: 'practica-flutter-firebase-arce',
    storageBucket: 'practica-flutter-firebase-arce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNvBD6Gf7bfesaep8Paxdtxxl2tmh1Xuc',
    appId: '1:310448288775:ios:fc470bdf77f955e4a9a6a2',
    messagingSenderId: '310448288775',
    projectId: 'practica-flutter-firebase-arce',
    storageBucket: 'practica-flutter-firebase-arce.appspot.com',
    iosClientId: '310448288775-rrig96g0nqh205itm0qld6d3mhacfmj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNvBD6Gf7bfesaep8Paxdtxxl2tmh1Xuc',
    appId: '1:310448288775:ios:fc470bdf77f955e4a9a6a2',
    messagingSenderId: '310448288775',
    projectId: 'practica-flutter-firebase-arce',
    storageBucket: 'practica-flutter-firebase-arce.appspot.com',
    iosClientId: '310448288775-rrig96g0nqh205itm0qld6d3mhacfmj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
